- src/main/java/me/confuser/banmanager/commands/WarnCommand.java
> Fix warning actions

- src/main/java/me/confuser/banmanager/configs/DefaultConfig.java
- src/main/java/me/confuser/banmanager/storage/conversion/converters/Converter.java
- src/main/java/me/confuser/banmanager/util/UUIDUtils.java
- src/main/resources/config.yml
Adds a config option for offline-mode support.
Feel free to edit config location, as this also changes normal UUIDProfile lookups.
Duplicate usernames should not occur in offline-mode.
Not tested with users changing capitals from their username.
> Basic offline-mode support.

- pom.xml
- src/main/java/me/confuser/banmanager/BanManager.java
- src/main/java/me/confuser/banmanager/commands/AutoCompleteNameTabCommand.java
- src/main/java/me/confuser/banmanager/commands/BanIpRangeCommand.java
- src/main/java/me/confuser/banmanager/commands/SyncCommand.java
- src/main/java/me/confuser/banmanager/commands/TempIpRangeBanCommand.java
- src/main/java/me/confuser/banmanager/commands/UnbanIpRangeCommand.java
- src/main/java/me/confuser/banmanager/configs/LocalDatabaseConfig.java
- src/main/java/me/confuser/banmanager/data/IpRangeBanData.java
- src/main/java/me/confuser/banmanager/data/IpRangeBanRecord.java
- src/main/java/me/confuser/banmanager/events/IpRangeBanEvent.java
- src/main/java/me/confuser/banmanager/events/IpRangeUnbanEvent.java
- src/main/java/me/confuser/banmanager/listeners/BanListener.java
- src/main/java/me/confuser/banmanager/listeners/JoinListener.java
- src/main/java/me/confuser/banmanager/runnables/ExpiresSync.java
- src/main/java/me/confuser/banmanager/runnables/IpRangeSync.java
- src/main/java/me/confuser/banmanager/storage/IpRangeBanRecordStorage.java
- src/main/java/me/confuser/banmanager/storage/IpRangeBanStorage.java
- src/main/java/me/confuser/banmanager/util/IPUtils.java
- src/main/resources/config.yml
- src/main/resources/messages.yml
- src/main/resources/plugin.yml
- src/main/resources/schedules.yml
Supports CIDR and wildcard notations
> IP Range Banning

- src/main/resources/config.yml
> Fixes https://github.com/BanManagement/BanManager/issues/369

- src/main/java/me/confuser/banmanager/util/CommandUtils.java
Checking for isCreateNoteReasons before autogenerating notes
> Using createNoteReasons

- src/main/java/me/confuser/banmanager/util/CommandUtils.java
Fixing error: cannot find symbol class DefaultConfig and illegal start
of type on Jenkins
> Bugfix class symbol

- src/main/java/me/confuser/banmanager/util/DateUtils.java
Fixed a wrong calculation (+ 1 day at the end of a month)
> Calculation fix

- src/main/java/me/confuser/banmanager/configs/DatabaseConfig.java
This is required according to MySQL 5.5.45+, 5.6.26+ and 5.7.6+.
> Added useSSL=false to JDBC connection URL

- pom.xml
I updated the Maven repositories so that the plugin will compile again.
> Updated repositories

- README.md
> Make the build status appear on another line

- bukkit/pom.xml
- bukkit/src/main/java/me/confuser/banmanager/bukkit/api/events/PlayerKickedEvent.java
- common/src/main/java/me/confuser/banmanager/common/commands/KickCommand.java
- common/src/main/java/me/confuser/banmanager/common/storage/PlayerKickStorage.java
- sponge/src/main/java/me/confuser/banmanager/sponge/api/events/PlayerKickedEvent.java
> feat: added PlayerKickedEvent

- common/pom.xml
- common/src/main/java/me/confuser/banmanager/common/commands/InfoCommand.java
- common/src/main/java/me/confuser/banmanager/common/configs/GeoIpConfig.java
- common/src/main/resources/geoip.yml
> refactor: add license key support to MaxMind Lite

- common/src/main/java/me/confuser/banmanager/common/commands/CommonCommand.java
Currently doesn't display correct suggestions for multiple reasons
> fix: correctly handle tab complete for multiple reasons in one command

- common/src/main/java/me/confuser/banmanager/common/listeners/CommonJoinListener.java
Description is inside the commits.
> Fix NPE checks

- bukkit/src/main/java/me/confuser/banmanager/bukkit/BukkitPlayer.java
- bungee/src/main/java/me/confuser/banmanager/bungee/BungeePlayer.java
- common/src/main/java/me/confuser/banmanager/common/util/Message.java
- sponge/src/main/java/me/confuser/banmanager/sponge/SpongePlayer.java
There are some places where empty message could still be sent.
> fix: do not send empty messages

- common/src/main/java/me/confuser/banmanager/common/BanManagerPlugin.java
> Remove rewriteBatchedStatements property

- common/src/main/java/me/confuser/banmanager/common/commands/InfoCommand.java
I just fixed two empty catch blocks in InfoCommand, that's all.
> Swallow two fewer exceptions

- velocity/src/main/java/me.confuser.banmanager.velocity/VelocityCommand.java
- fixed permission behaviour
made a oopsie, noticed it today. Im sry for the trouble
> Velocity-Permissions

- velocity/src/main/java/me.confuser.banmanager.velocity/VelocityScheduler.java
Fixed VelocityScheduler for WebEnhancer by replacing the BMVelocityPlugin pass to the constructor. Needed for WebEnhancer
(sry for the mistake, hopefully the last one)
Also need it on maven ^^''
> fixed VelocityScheduler

- velocity/build.gradle.kts
> fix(velocity): relocate bstats correctly
